/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Placauto.visual;

import com.Placauto.classesAdversas.ControlerLog;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Jonas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void comandoTela(JInternalFrame frame) {
        boolean jaExiste = false;
        try {
            for (JInternalFrame internal : Desktop.getAllFrames()) {
                if (internal.getClass().toString().equalsIgnoreCase(frame.getClass().toString())) {
                    frame.setSelected(true);
                    jaExiste = true;
                } else {
                    frame.setSelected(true);
                }
            }
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(jaExiste){
            return;
        }
        
        Desktop.add(frame);
        frame.setVisible(true);
        try {
            ControlerLog log = new ControlerLog();
            log.writeLog("log.txt", frame.getTitle());
        } catch (Exception ex) {
            new ControlerLog().writeStackTrace(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuCadastroCliente = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuCadastrarFornecedor = new javax.swing.JMenuItem();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuCadastrarFuncionarios = new javax.swing.JMenuItem();
        jMenuItens = new javax.swing.JMenu();
        jMenuCadastrarItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Placauto");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jMenuClientes.setText("Clientes");
        jMenuClientes.setName(""); // NOI18N

        jMenuCadastroCliente.setText("Cadastrar Cliente");
        jMenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuCadastroCliente);

        jMenu.add(jMenuClientes);

        jMenuFornecedores.setText("Fornecedores");

        jMenuCadastrarFornecedor.setText("Cadastrar Fornecedor");
        jMenuCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuCadastrarFornecedor);

        jMenu.add(jMenuFornecedores);

        jMenuFuncionario.setText("Funcionários");

        jMenuCadastrarFuncionarios.setText("Cadastrar Funcionarios");
        jMenuCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFuncionariosActionPerformed(evt);
            }
        });
        jMenuFuncionario.add(jMenuCadastrarFuncionarios);

        jMenu.add(jMenuFuncionario);

        jMenuItens.setText("Itens");

        jMenuCadastrarItem.setText("Cadastrar Itens");
        jMenuCadastrarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarItemActionPerformed(evt);
            }
        });
        jMenuItens.add(jMenuCadastrarItem);

        jMenu.add(jMenuItens);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClienteActionPerformed
        /* ControlerLog control = new ControlerLog();
        try {
            control.writeLog("log.txt", "Cadastro de Cliente");
        } catch (IOException ex) {
            new ControlerLog().writeStackTrace(ex);
        }
        CadastroCliente cc = new CadastroCliente();
        Desktop.add(cc);
        cc.setVisible(true);*/
        
        comandoTela(new CadastroCliente());


    }//GEN-LAST:event_jMenuCadastroClienteActionPerformed

    private void jMenuCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFornecedorActionPerformed
//        ControlerLog control = new ControlerLog();
//        try {
//            control.writeLog("log.txt", "Cadastro de Fornecedor");
//        } catch (IOException ex) {
//            new ControlerLog().writeStackTrace(ex);
//        }
//        CadastroFornecedor cf = new CadastroFornecedor();
//        Desktop.add(cf);
//        cf.setVisible(true);
//        
        comandoTela(new CadastroFornecedor());
    }//GEN-LAST:event_jMenuCadastrarFornecedorActionPerformed

    private void jMenuCadastrarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarItemActionPerformed
        /*ControlerLog control = new ControlerLog();
        try {
            control.writeLog("log.txt", "Cadastro de Itens");
        } catch (IOException ex) {
            new ControlerLog().writeStackTrace(ex);
        }
        CadastroItens ci = new CadastroItens();
        Desktop.add(ci);
        ci.setVisible(true);*/
        
        comandoTela(new CadastroItens());
    }//GEN-LAST:event_jMenuCadastrarItemActionPerformed

    private void jMenuCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFuncionariosActionPerformed
        /* ControlerLog control = new ControlerLog();
        try {
            control.writeLog("log.txt", "Cadastro de Funcionário");
        } catch (IOException ex) {
            new ControlerLog().writeStackTrace(ex);
        }
        CadastroFuncionario cadfunc = new CadastroFuncionario();
        Desktop.add(cadfunc);
        cadfunc.setVisible(true);*/

        comandoTela(new CadastroFuncionario());

    }//GEN-LAST:event_jMenuCadastrarFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Principal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuCadastrarFornecedor;
    private javax.swing.JMenuItem jMenuCadastrarFuncionarios;
    private javax.swing.JMenuItem jMenuCadastrarItem;
    private javax.swing.JMenuItem jMenuCadastroCliente;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenu jMenuItens;
    // End of variables declaration//GEN-END:variables
}
