/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Placauto.visual;

import com.Placauto.visual.CadastroCliente;
import com.Placauto.visual.CadastroFornecedor;
import com.Placauto.visual.CadastroItens;
import com.Placauto.visual.CadastroFuncionario;
/**
 *
 * @author Jonas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuCadastroCliente = new javax.swing.JMenuItem();
        jMenuCadastrarFornecedor = new javax.swing.JMenuItem();
        jMenuCadastrarItem = new javax.swing.JMenuItem();
        jMenuCadastrarFuncionarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Placauto");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jMenuCadastrar.setText("Cadastrar");

        jMenuCadastroCliente.setText("Cadastrar Cliente");
        jMenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClienteActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastroCliente);

        jMenuCadastrarFornecedor.setText("Cadastrar Fornecedor");
        jMenuCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastrarFornecedor);

        jMenuCadastrarItem.setText("Cadastrar Itens");
        jMenuCadastrarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarItemActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastrarItem);

        jMenuCadastrarFuncionarios.setText("Cadastrar Funcionarios");
        jMenuCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrarFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastrarFuncionarios);

        jMenu.add(jMenuCadastrar);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClienteActionPerformed
        CadastroCliente cc = new CadastroCliente();
        Desktop.add(cc);
        cc.setVisible(true);
       
    }//GEN-LAST:event_jMenuCadastroClienteActionPerformed

    private void jMenuCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFornecedorActionPerformed
        CadastroFornecedor cf = new CadastroFornecedor();
        Desktop.add(cf);
        cf.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarFornecedorActionPerformed

    private void jMenuCadastrarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarItemActionPerformed
        CadastroItens ci = new CadastroItens();
        Desktop.add(ci);
        ci.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarItemActionPerformed

    private void jMenuCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrarFuncionariosActionPerformed
       CadastroFuncionario cadfunc = new CadastroFuncionario();
       Desktop.add(cadfunc);
       cadfunc.setVisible(true);
    }//GEN-LAST:event_jMenuCadastrarFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuCadastrarFornecedor;
    private javax.swing.JMenuItem jMenuCadastrarFuncionarios;
    private javax.swing.JMenuItem jMenuCadastrarItem;
    private javax.swing.JMenuItem jMenuCadastroCliente;
    // End of variables declaration//GEN-END:variables
}
